# SPDX-FileCopyrightText: 2022 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
# https://github.com/dependabot/dependabot-core/issues/6888
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    registries: "*"
    open-pull-requests-limit: 99
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    cooldown:
      default-days: 7
