# SPDX-FileCopyrightText: 2022 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

junit.jupiter.execution.timeout.testable.method.default = 2s
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = concurrent
