/*
 * SPDX-FileCopyrightText: 2024 Lukas Pieper
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package de.lukaspieper.truvark.ui.theme

import androidx.compose.ui.graphics.Color

public val md_theme_light_primary: Color = Color(0xFF006E1C)
public val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_light_primaryContainer: Color = Color(0xFF94F990)
public val md_theme_light_onPrimaryContainer: Color = Color(0xFF002204)
public val md_theme_light_secondary: Color = Color(0xFF52634F)
public val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_light_secondaryContainer: Color = Color(0xFFD5E8CF)
public val md_theme_light_onSecondaryContainer: Color = Color(0xFF111F0F)
public val md_theme_light_tertiary: Color = Color(0xFF38656A)
public val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
public val md_theme_light_tertiaryContainer: Color = Color(0xFFBCEBF0)
public val md_theme_light_onTertiaryContainer: Color = Color(0xFF002023)
public val md_theme_light_error: Color = Color(0xFFBA1A1A)
public val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_light_onError: Color = Color(0xFFFFFFFF)
public val md_theme_light_onErrorContainer: Color = Color(0xFF410002)
public val md_theme_light_background: Color = Color(0xFFFCFDF6)
public val md_theme_light_onBackground: Color = Color(0xFF1A1C19)
public val md_theme_light_surface: Color = Color(0xFFFCFDF6)
public val md_theme_light_onSurface: Color = Color(0xFF1A1C19)
public val md_theme_light_surfaceVariant: Color = Color(0xFFDEE5D8)
public val md_theme_light_onSurfaceVariant: Color = Color(0xFF424940)
public val md_theme_light_outline: Color = Color(0xFF72796F)
public val md_theme_light_inverseOnSurface: Color = Color(0xFFF0F1EB)
public val md_theme_light_inverseSurface: Color = Color(0xFF2F312D)
public val md_theme_light_inversePrimary: Color = Color(0xFF78DC77)
public val md_theme_light_shadow: Color = Color(0xFF000000)
public val md_theme_light_surfaceTint: Color = Color(0xFF006E1C)
public val md_theme_light_outlineVariant: Color = Color(0xFFC2C9BD)
public val md_theme_light_scrim: Color = Color(0xFF000000)

public val md_theme_dark_primary: Color = Color(0xFF78DC77)
public val md_theme_dark_onPrimary: Color = Color(0xFF00390A)
public val md_theme_dark_primaryContainer: Color = Color(0xFF005313)
public val md_theme_dark_onPrimaryContainer: Color = Color(0xFF94F990)
public val md_theme_dark_secondary: Color = Color(0xFFBACCB3)
public val md_theme_dark_onSecondary: Color = Color(0xFF253423)
public val md_theme_dark_secondaryContainer: Color = Color(0xFF3B4B38)
public val md_theme_dark_onSecondaryContainer: Color = Color(0xFFD5E8CF)
public val md_theme_dark_tertiary: Color = Color(0xFFA0CFD4)
public val md_theme_dark_onTertiary: Color = Color(0xFF00363B)
public val md_theme_dark_tertiaryContainer: Color = Color(0xFF1F4D52)
public val md_theme_dark_onTertiaryContainer: Color = Color(0xFFBCEBF0)
public val md_theme_dark_error: Color = Color(0xFFFFB4AB)
public val md_theme_dark_errorContainer: Color = Color(0xFF93000A)
public val md_theme_dark_onError: Color = Color(0xFF690005)
public val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_dark_background: Color = Color(0xFF1A1C19)
public val md_theme_dark_onBackground: Color = Color(0xFFE2E3DD)
public val md_theme_dark_surface: Color = Color(0xFF1A1C19)
public val md_theme_dark_onSurface: Color = Color(0xFFE2E3DD)
public val md_theme_dark_surfaceVariant: Color = Color(0xFF424940)
public val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC2C9BD)
public val md_theme_dark_outline: Color = Color(0xFF8C9388)
public val md_theme_dark_inverseOnSurface: Color = Color(0xFF1A1C19)
public val md_theme_dark_inverseSurface: Color = Color(0xFFE2E3DD)
public val md_theme_dark_inversePrimary: Color = Color(0xFF006E1C)
public val md_theme_dark_shadow: Color = Color(0xFF000000)
public val md_theme_dark_surfaceTint: Color = Color(0xFF78DC77)
public val md_theme_dark_outlineVariant: Color = Color(0xFF424940)
public val md_theme_dark_scrim: Color = Color(0xFF000000)

public val seed: Color = Color(0xFF4CAF50)
