# SPDX-FileCopyrightText: 2022 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: continuous

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions: {}

jobs:
  detekt:
    uses: ./.github/workflows/lint-detekt.yml
    permissions:
      security-events: read

  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/assembleDebug.yml

  jvmtests:
    uses: ./.github/workflows/tests-jvm.yml

  licensing:
    name: Run License Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint licensing
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0
