# SPDX-FileCopyrightText: 2025 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run Detekt Linter workflow

on: [workflow_call]

jobs:
  detekt:
    name: Run Detekt Linter
    runs-on: ubuntu-latest
    permissions:
      security-events: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Setup
      uses: ./.github/actions/setup

    - name: Run Detekt
      run: ./gradlew detekt

    - name: Upload Markdown Report
      if: success() || failure()
      run: |
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Show Report</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY

    - name: Upload HTML Reports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: success() || failure()
      with:
        name: Detekt-HTML
        path: build/reports/detekt/detekt.html

    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
      if: success() || failure()
      with:
        sarif_file: build/reports/detekt/detekt.sarif
