# SPDX-FileCopyrightText: 2025 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run Android Linter workflow

on: [workflow_call]

jobs:
  lint:
    name: Run Android Linter
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Run Lint
      run: ./gradlew lint

    - name: Upload Markdown Report
      if: success() || failure()
      run: |
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Show Report</summary>" >> $GITHUB_STEP_SUMMARY
        sed -n '/<body/,/<\/body>/p' **/build/reports/lint-results-debug.html >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY

    - name: Upload HTML Reports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: success() || failure()
      with:
        name: Lint-HTML
        path: '**/build/reports/lint-results-debug.html'
