# SPDX-FileCopyrightText: 2022 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run JVM Tests workflow

on: [workflow_call]

jobs:
  jvmtests:
    name: Run JVM Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup
      uses: ./.github/actions/setup

    - name: Run JVM Tests
      run: ./gradlew shared:jvmTest

    - name: Upload Markdown Report
      if: success() || failure()
      run: |
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Show Report</summary>" >> $GITHUB_STEP_SUMMARY
        sed -n '/<body>/,/<\/body>/p' shared/build/reports/tests/jvmTest/index.html >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY

    - name: Upload HTML Reports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: success() || failure()
      with:
        name: Tests-HTML
        path: shared/build/reports/tests
